# Generated by Django 4.2.2 on 2023-06-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profil_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
