# Generated by Django 4.2.1 on 2023-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0002_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='none@cw.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
