# Generated by Django 4.2.2 on 2023-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='clarusway.png', null=True, upload_to='product/'),
        ),
    ]
